Adds the cheat sheet tab
AllPurposeName/fabula-ultima-foundry-vtt pull request #44
Opened 2023-12-30 13:24 UTC by siegfault

Moving some info into (unstyled) tooltips, this adds the rest into its own tab. The dedicated tab only lists available actions as well as opportunities, but it includes everything from the reference doc with the exception of checks. I feel like that's mostly useful for a DM, so I'm not sure whether it should go on there, but I have no problem adding it. To also add is a custom area for notes maybe?

Of note, removing the custom css causes the pronouns section not to run up into the tabs. Some formatting still needs to be done however.

[screen-capture.webm](https://github.com/AllPurposeName/fabula-ultima-foundry-vtt/assets/1421705/6e0bf2dc-1967-46e6-a498-f86f2ed7fd62)

2023-12-30 15:47 UTC, mbenfowler commented
> Moving some info into (unstyled) tooltips

This confuses me, where are these tooltips?

2023-12-30 16:17 UTC, mbenfowler commented on src/actor/character/sheets-tabs/cheat-sheet.hbs
Where do all these icons come from? Is there an easy place to see what we have available to us?

2023-12-30 16:25 UTC, mbenfowler requested changes

2023-12-30 16:25 UTC, mbenfowler commented on static/lang/en.json
> +  "INVENTORY.ELEMENTAL_SHARD": "Elemental Shard (2 IP): One creature suffers 10 damage of a type of your choice (ait, bolt, earth, fire, or ice).",
air?

2023-12-30 16:25 UTC, mbenfowler commented on static/lang/en.json
> +  "OPPORTUNITY.AFFLICTION": "Affliction: a creature sufferes dazed, shaken, slow, or weak (see page 94).",
suffers

2023-12-30 16:25 UTC, mbenfowler commented on static/lang/en.json
> +  "OPPORTUNITY.BONDING": "Bonding: you create a Bond towards someone or something or add an emtotion to one of your existing Bonds (see page 56).",
emotion

2023-12-30 16:25 UTC, mbenfowler commented on static/lang/en.json
> +  "OPPORTUNITY.FAUX_PAS": "Faux Pas: choose a creature present on the scene: they make a compromising statement chosen by the person who controls them.",
Damn we should always make DJ do this one XD

2023-12-30 16:25 UTC, mbenfowler commented on static/lang/en.json
> +  "OPPORTUNITY.PLOT_TWIST": "Plot Twist!: someone or something of your choice suddently appears on the scene.",
suddenly

2023-12-31 00:35 UTC, siegfault commented on src/actor/character/sheets-tabs/cheat-sheet.hbs
Yup! They all come from https://fontawesome.com/. There's a search to find specific ones since they have 30k+

2023-12-31 00:45 UTC, siegfault commented
Re: typos, lmao that's what I get for pushing at 5am.

Re: tooltips, those come from the title attribute. They currently look like this: 
![Screenshot from 2023-12-30 17-36-23](https://github.com/AllPurposeName/fabula-ultima-foundry-vtt/assets/1421705/d5306f87-5bbe-4f85-91d9-8814fd3e3e05)

Thanks for adding those styles :heart:

2023-12-31 01:51 UTC, AllPurposeName approved these changes

2023-12-31 07:20 UTC, siegfault commented
Going to merge as is, and create a followup for the tooltips which I think are the main thing that still need work

2023-12-31 07:20 UTC, merged

2023-12-31 07:21 UTC, siegfault commented
Followup: https://github.com/AllPurposeName/fabula-ultima-foundry-vtt/issues/45